version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded_images:/app/uploaded_images
    depends_on:
      - ollama
    networks:
      - tutorial-net

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - tutorial-vol:/root/.ollama
    networks:
      - tutorial-net
    entrypoint: ["/usr/bin/bash", "/pull-gemma3.sh"]

networks:
  tutorial-net:
    driver: bridge

volumes:
  tutorial-vol:
    driver: local